### ISSUE TITLE
Success and error functions are deprecated for newer angular versions

### ISSUE THREAD

**Issue by cabaird** [kinstephen/angular-azure-blob-upload#15]
In newer versions of angular, the success and error functions, which were the legacy functions used by promises, are deprecated.  As a result, these functions are not defined, and your code gives errors on lines `43`, `53`, `153`, and `158`.

There is already a pull request for the code change.

https://github.com/kinstephen/angular-azure-blob-upload/pull/14

Please review that request and make the change.

Thank you

**Comment by kinstephen** [comment]
Done
