### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by andrewmcwatters** [kinstephen/angular-azure-blob-upload#4]
Hey Stephen,

Could you [register](http://bower.io/docs/creating-packages/) this with `bower`? Would be pretty cool to include this in webapp projects without downloading the file manually.

Andrew

**Comment by kinstephen** [comment]
Yup certainly. I'll see what I can do. Might take me some time as I've never used bower before.

**Comment by andrewmcwatters** [comment]
Awesome! No rush or anything, and it's not that big of a deal if you choose not to. Just thought it would be cool.
