### ISSUE TITLE
405 (The resource doesn't support specified Http Verb.)

### ISSUE THREAD

**Issue by krusk** [kinstephen/angular-azure-blob-upload#6]
I am using the following to attempt to upload to Azure Blob storage along with the Angular Azure Blob Upload script, but am receiving a 405 (The resource doesn't support specified Http Verb.). If I change it to a PUT method, it gives me a Cross Origin error even though CORS is enabled and I am using a public container for testing purposes. Any clues? Is SAS required for upload, and if so, can you show an example of a config per your directive?

    $scope.reRender = function () {
        var canvasImage = document.getElementById("c");
        var img = canvasImage.toDataURL("image/png");
        var filename = 'Test';

        var formdata = new FormData();
        formdata.append(filename, img);

        var send = function (blob) {
            var filename = 'Test.png';
            var formdata = new FormData();
            formdata.append('File1', blob, filename);

            $.ajax({
                url: 'http://myblob.blob.core.windows.net/blob1',
                type: "POST",
                data: formdata,
                mimeType: "multipart/form-data",
                processData: false,
                contentType: false,
                crossDomain: true,
                success: function (result) {
                    console.log("Upload to Azure complete!");
                },
                error: function (error) {
                    console.log("Something went wrong!");
                }
            })
        }

        var canvasImage = document.getElementById("c");
        if (!canvasImage.toBlob) {
            var dataURL = canvasImage.toDataURL();
            var bytes = atob(dataURL.split(',')[1])
            var arr = new Uint8Array(bytes.length);
            for (var i = 0; i < bytes.length; i++) {
                arr[i] = bytes.charCodeAt(i);
            }
            send(new Blob([arr], { type: 'image/png' }));
        }
        else
            canvasImage.toBlob(send);
    }

**Comment by kinstephen** [comment]
Yes it requires CORS in order to work with it. The introduction page has links to how to setup CORS.
