### ISSUE TITLE
Multithreading Upload for Blob Upload

### ISSUE THREAD

**Issue by vjustin** [kinstephen/angular-azure-blob-upload#7]
Dear Sir,

I started using angular-azure-blob-upload and to speed up the uploading speed i have configured the maximum blockSize of 4194304. Still it takes 2 minutes to upload 236 MB file size. So I'm are looking for an option to multithreaded upload. How to achive it using this component. Please Guide.

Thanks,
Viji

**Comment by kinstephen** [comment]
I believe Azure Blob storage has a concept of uploading in blocks. A good starting point for this is https://msdn.microsoft.com/en-us/library/azure/ee691974.aspx and https://msdn.microsoft.com/en-us/library/azure/ee691964.aspx You will have to add support for block blobs. This component does not support block blobs at this time.
