### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ElvisMagagula** [kinstephen/angular-azure-blob-upload#8]
Create an example dude else whats the point of sharing?

**Comment by kinstephen** [comment]
Wow harsh but ok. I will when I have time. Which unfortunately I do not know when that will be. 

Also the point of sharing is to make it available to everyone. The code isn't complex if your familiar with AngularJS.

**Comment by kinstephen** [comment]
Btw this is a duplicate issue on here. Closing it.

**Comment by ElvisMagagula** [comment]
Thank you for replying, I didnt mean to be harsh, perhaps I can get it to
work and help out with the read me If you do not get the time?

**Comment by kinstephen** [comment]
Certainly of course! Your welcome to contribute. It's very much appreciated!
